### ISSUE TITLE
deterministic wallet

### ISSUE THREAD

**Issue by quinnoaj** [prusnak/addrgen#13]
Hello is this for hierarchical or sequential deterministic wallet type?

*sorry I don't know where to ask.

**Comment by prusnak** [comment]
Sequential

**Comment by quinnoaj** [comment]
it only accept the pub key as input for generating sd addresses? or it can accept strings?
Thank you for responding to my question.

**Comment by prusnak** [comment]
Pubkey in hex format, such as `675b7041a347223984750fe3ab229df0c9f960e7ec98226b7182a2cb1990e39901feecf5a670f1d788ab29f626e20de424f049d216fc6f4c6ec42506763fa28e`
